rootProject.name = 'timeline'

include 'libs:common-events'
include 'libs:common-outbox'
include 'libs:common-web'

include 'services:api-gateway'
include 'services:team-service'
include 'services:schedule-service'
include 'services:backlog-service'
include 'services:planning-service'
include 'services:timeline-bff'
